FROM debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git postgresql ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN service postgresql start 

CMD ["postgres"]
