FROM debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git nginx && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN git clone --depth 1 https://github.com/SlinkySoftware/DeviceVault.git repo

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

RUN cp -r /app/repo/frontend/* /var/www/html/
ENTRYPOINT ["/app/repo/frontend/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
