FROM debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git redis-server ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["redis-server", "--bind", "0.0.0.0"]
