# Generated by Django 6.0 on 2026-01-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplocation',
            name='config',
            field=models.JSONField(default=dict, help_text='Location-specific configuration (URL, credentials, path, etc.)'),
        ),
        migrations.AlterField(
            model_name='backuplocation',
            name='location_type',
            field=models.CharField(help_text='Type of location: git, s3, filesystem, tftp, etc.', max_length=64),
        ),
        migrations.AlterField(
            model_name='backuplocation',
            name='name',
            field=models.CharField(help_text='Display name for this backup location', max_length=128),
        ),
    ]
