# Generated by Django 6.0 on 2026-01-06 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_label'),
        ('credentials', '__first__'),
        ('locations', '__first__'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.CharField(blank=True, default='router', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('dns_name', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('last_backup_time', models.DateTimeField(blank=True, null=True)),
                ('last_backup_status', models.CharField(blank=True, max_length=32)),
                ('backup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.backuplocation')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.credential')),
                ('labels', models.ManyToManyField(blank=True, to='core.label')),
                ('retention_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.retentionpolicy')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.devicetype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.manufacturer')),
            ],
        ),
    ]
