# Generated by Django 6.0 on 2026-01-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_add_icon_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_example_data',
            field=models.BooleanField(default=False, help_text='Mark as example data to exclude from backup processing'),
        ),
    ]
