# Generated by Django 6.0 on 2026-01-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dashboardlayout_created_at_and_more'),
        ('credentials', '0002_alter_credential_credential_type_and_more'),
        ('devices', '0003_device_is_example_data'),
        ('locations', '0002_alter_backuplocation_config_and_more'),
        ('policies', '0002_alter_backupschedule_created_at_and_more'),
        ('rbac', '0005_devicegroup_devicegrouppermission_devicegrouprole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_group',
            field=models.ForeignKey(blank=True, help_text='Device group for RBAC access control', null=True, on_delete=django.db.models.deletion.PROTECT, to='rbac.devicegroup'),
        ),
        migrations.AlterField(
            model_name='device',
            name='backup_location',
            field=models.ForeignKey(blank=True, help_text='Where to store backups', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.backuplocation'),
        ),
        migrations.AlterField(
            model_name='device',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='SSH/Telnet credentials for device access', null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.credential'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(help_text='Type of device (Router, Switch, etc.)', on_delete=django.db.models.deletion.PROTECT, to='devices.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='dns_name',
            field=models.CharField(blank=True, help_text='FQDN for DNS resolution (optional)', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable this device for backups'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IPv4 address for SSH/Telnet connection', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_example_data',
            field=models.BooleanField(default=False, help_text='Mark as example/demo data to exclude from backups'),
        ),
        migrations.AlterField(
            model_name='device',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Tags for organization (deprecated, kept for migration)', to='core.label'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_backup_status',
            field=models.CharField(blank=True, help_text='Status of last backup: success, failed, pending, etc.', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_backup_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful backup', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(help_text='Hardware manufacturer', on_delete=django.db.models.deletion.PROTECT, to='devices.manufacturer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Device hostname or identifier', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='retention_policy',
            field=models.ForeignKey(blank=True, help_text='Backup retention policy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.retentionpolicy'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon',
            field=models.CharField(blank=True, default='router', help_text='Material Design icon name', max_length=64),
        ),
    ]
