# Generated by Django 6.0 on 2026-01-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_device_group_alter_device_backup_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='labels',
        ),
    ]
