# Generated by Django 6.0 on 2026-01-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_devicegroup_options_and_more'),
    ]

    operations = []
