# Generated by Django 6.0 on 2026-01-07 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_devicegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegrouprole',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When role was created', null=True),
        ),
    ]
