# Generated by Django 6.0 on 2026-01-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_devicegrouprole_created_at'),
    ]

    operations = []
