# Generated by Django 6.0 on 2026-01-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_ensure_devicegroup_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_example_data',
        ),
    ]
