# Generated by Django 5.2.10 on 2026-01-08 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('devices', '0014_remove_is_example_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique collection group name', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the collection group purpose')),
                ('rabbitmq_queue_id', models.CharField(help_text='RabbitMQ queue ID for task distribution', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When group was last modified')),
            ],
            options={
                'verbose_name': 'Collection Group',
                'verbose_name_plural': 'Collection Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='devicegroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devicegrouprole',
            options={'ordering': ['device_group', 'name'], 'verbose_name': 'Device Group Role', 'verbose_name_plural': 'Device Group Roles'},
        ),
        migrations.AlterModelOptions(
            name='groupdevicegrouprole',
            options={'verbose_name': 'Group Device Group Role', 'verbose_name_plural': 'Group Device Group Roles'},
        ),
        migrations.AlterModelOptions(
            name='userdevicegrouprole',
            options={'verbose_name': 'User Device Group Role', 'verbose_name_plural': 'User Device Group Roles'},
        ),
        migrations.AlterUniqueTogether(
            name='devicegrouprole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devicegroupdjangopermissions',
            name='perm_backup_now',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dg_perm_backup_now', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_group',
            field=models.ForeignKey(blank=True, help_text='Device group for RBAC access control', null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.devicegroup'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When group was created'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the device group purpose'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='name',
            field=models.CharField(help_text='Unique device group name', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When group was last modified'),
        ),
        migrations.AlterField(
            model_name='devicegroupdjangopermissions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicegrouppermission',
            name='code',
            field=models.CharField(help_text='Unique permission code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='devicegrouppermission',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this permission allows'),
        ),
        migrations.AlterField(
            model_name='devicegrouppermission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicegrouppermission',
            name='name',
            field=models.CharField(help_text='Human-readable permission name', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicegrouprole',
            name='description',
            field=models.TextField(help_text='Description of the role'),
        ),
        migrations.AlterField(
            model_name='devicegrouprole',
            name='device_group',
            field=models.ForeignKey(help_text='Device group this role applies to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='devices.devicegroup'),
        ),
        migrations.AlterField(
            model_name='devicegrouprole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicegrouprole',
            name='name',
            field=models.CharField(help_text='Role name within the device group', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicegrouprole',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions granted by this role', related_name='roles', to='devices.devicegrouppermission'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupdevicegrouprole',
            name='auth_group',
            field=models.ForeignKey(help_text='Django auth group', on_delete=django.db.models.deletion.CASCADE, related_name='device_group_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='groupdevicegrouprole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupdevicegrouprole',
            name='role',
            field=models.ForeignKey(help_text='Device group role to assign', on_delete=django.db.models.deletion.CASCADE, to='devices.devicegrouprole'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdevicegrouprole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdevicegrouprole',
            name='role',
            field=models.ForeignKey(help_text='Device group role to assign', on_delete=django.db.models.deletion.CASCADE, to='devices.devicegrouprole'),
        ),
        migrations.AlterField(
            model_name='userdevicegrouprole',
            name='user',
            field=models.ForeignKey(help_text='User being assigned a role', on_delete=django.db.models.deletion.CASCADE, related_name='device_group_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='devicegrouprole',
            unique_together={('name', 'device_group')},
        ),
        migrations.AlterModelTable(
            name='devicegroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='devicegroupdjangopermissions',
            table=None,
        ),
        migrations.AlterModelTable(
            name='groupdevicegrouprole',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userdevicegrouprole',
            table=None,
        ),
        migrations.AddField(
            model_name='device',
            name='collection_group',
            field=models.ForeignKey(blank=True, help_text='Collection group for task distribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.collectiongroup'),
        ),
    ]
