# Generated by Django 5.2.10 on 2026-01-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_collectiongroup_alter_devicegroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBackupResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64)),
                ('task_identifier', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('log', models.TextField(help_text='JSON serialized list of log messages')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
