# Generated by Django 5.2.10 on 2026-01-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_devicebackupresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebackupresult',
            name='collection_duration_ms',
            field=models.IntegerField(blank=True, help_text='Collection execution time in milliseconds (step 3)', null=True),
        ),
        migrations.AddField(
            model_name='devicebackupresult',
            name='initiated_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when backup was initiated (step 1)', null=True),
        ),
        migrations.AddField(
            model_name='devicebackupresult',
            name='overall_duration_ms',
            field=models.IntegerField(blank=True, help_text='Overall processing time from initiation to completion in milliseconds', null=True),
        ),
    ]
