# Generated by Django 5.2.10 on 2026-01-14 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_devicebackupresult_collection_duration_ms_and_more'),
        ('policies', '0003_backupschedule_last_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='backup_schedule',
            field=models.ForeignKey(blank=True, help_text='Automated backup schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.backupschedule'),
        ),
    ]
