# Generated by Django 6.0 on 2026-01-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='credential_type',
            field=models.ForeignKey(help_text='Source of credentials', on_delete=django.db.models.deletion.PROTECT, to='credentials.credentialtype'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='data',
            field=models.JSONField(default=dict, help_text='Credential data: username/password dict or vault connection params'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(help_text='Display name for this credential set', max_length=128),
        ),
        migrations.AlterField(
            model_name='credentialtype',
            name='name',
            field=models.CharField(help_text='Credential source type', max_length=64, unique=True),
        ),
    ]
