# Generated by Django 6.0 on 2026-01-07 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        ('devices', '0005_remove_device_labels'),
        ('locations', '0002_alter_backuplocation_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='artifact_path',
            field=models.CharField(help_text='Path or identifier of backup in storage location', max_length=256),
        ),
        migrations.AlterField(
            model_name='backup',
            name='device',
            field=models.ForeignKey(help_text='Device that was backed up', on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='is_text',
            field=models.BooleanField(default=True, help_text='True if text artifact (configs), False if binary'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='location',
            field=models.ForeignKey(help_text='Where this backup is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.backuplocation'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, help_text='Size of configuration backup in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(default='success', help_text='Backup status: success, failed, pending, etc.', max_length=32),
        ),
        migrations.AlterField(
            model_name='backup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When this backup was created'),
        ),
    ]
