# Generated by Django 6.0 on 2026-01-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_alter_backup_artifact_path_alter_backup_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When backup execution completed', null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='requested_at',
            field=models.DateTimeField(blank=True, help_text='When this backup was requested', null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When backup execution started', null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(default='pending', help_text='Backup status: pending, in_progress, success, failed', max_length=32),
        ),
        migrations.AlterField(
            model_name='backup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When this backup record was created'),
        ),
    ]
