# Generated by Django 5.2.10 on 2026-01-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_add_stored_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedbackup',
            name='storage_duration_ms',
            field=models.IntegerField(blank=True, help_text='Storage execution time in milliseconds (step 7)', null=True),
        ),
    ]
