# Generated by Django 6.0.2 on 2026-02-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0006_storedbackup_storage_duration_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedbackup',
            name='enc_cipher',
            field=models.CharField(blank=True, help_text='Cipher identifier, e.g. AES-256-GCM', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='storedbackup',
            name='enc_edk',
            field=models.TextField(blank=True, help_text='Encrypted DEK (base64-encoded)', null=True),
        ),
        migrations.AddField(
            model_name='storedbackup',
            name='enc_kid',
            field=models.CharField(blank=True, db_index=True, help_text='Master key identifier used to wrap the DEK', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='storedbackup',
            name='enc_version',
            field=models.IntegerField(blank=True, help_text='Encryption format version (null/0 = plaintext, 1 = AES-256-GCM chunked)', null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storedbackup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
