# Generated by Django 6.0 on 2026-01-07 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dashboardlayout_created_at_and_more'),
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(help_text='Unique permission identifier', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this permission allows'),
        ),
        migrations.AlterField(
            model_name='role',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Labels/environments this role can access', to='core.label'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Unique role name', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions granted to users with this role', to='rbac.permission'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(help_text='Role to assign', on_delete=django.db.models.deletion.CASCADE, to='rbac.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(help_text='User being assigned a role', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique group name', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Purpose and details of this group')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When group was last modified')),
                ('labels', models.ManyToManyField(blank=True, help_text='Tags/labels inherited by all group members', to='core.label')),
                ('users', models.ManyToManyField(blank=True, help_text='Users who are members of this group', related_name='vault_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
