# Generated by Django 6.0 on 2026-01-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_permission_code_alter_permission_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ignore_tags',
            field=models.BooleanField(default=False, help_text='Ignore tag-based access and filtering for this group'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_application_admin',
            field=models.BooleanField(default=False, help_text='Members see all Admin Settings pages'),
        ),
    ]
