# Generated by Django 6.0 on 2026-01-07 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_dashboardlayout_created_at_and_more'),
        ('rbac', '0003_group_ignore_tags_group_is_application_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLabelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the label was assigned to the group')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_assignments', to='auth.group')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='core.label')),
            ],
            options={
                'verbose_name': 'Group Label Assignment',
                'verbose_name_plural': 'Group Label Assignments',
                'unique_together': {('group', 'label')},
            },
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
