# Generated by Django 6.0 on 2026-01-07 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rbac', '0004_grouplabelassignment_delete_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique device group name', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the device group purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When group was last modified')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique permission code', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this permission allows')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name within the device group', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When role was created')),
                ('device_group', models.ForeignKey(help_text='Device group this role applies to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='rbac.devicegroup')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted by this role', to='rbac.devicegrouppermission')),
            ],
            options={
                'verbose_name': 'Device Group Role',
                'verbose_name_plural': 'Device Group Roles',
                'unique_together': {('name', 'device_group')},
            },
        ),
        migrations.CreateModel(
            name='GroupDeviceGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_group', models.ForeignKey(help_text='Django auth group', on_delete=django.db.models.deletion.CASCADE, related_name='device_group_roles', to='auth.group')),
                ('role', models.ForeignKey(help_text='Device group role to assign', on_delete=django.db.models.deletion.CASCADE, to='rbac.devicegrouprole')),
            ],
            options={
                'verbose_name': 'Group Device Group Role',
                'verbose_name_plural': 'Group Device Group Roles',
                'unique_together': {('auth_group', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserDeviceGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(help_text='Device group role to assign', on_delete=django.db.models.deletion.CASCADE, to='rbac.devicegrouprole')),
                ('user', models.ForeignKey(help_text='User being assigned a role', on_delete=django.db.models.deletion.CASCADE, related_name='device_group_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device Group Role',
                'verbose_name_plural': 'User Device Group Roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
