# Generated by Django 6.0 on 2026-01-07 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rbac', '0005_devicegroup_devicegrouppermission_devicegrouprole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroupDjangoRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='django_roles', to='rbac.devicegroup')),
                ('role_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_role_add', to='auth.group')),
                ('role_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_role_change', to='auth.group')),
                ('role_delete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_role_delete', to='auth.group')),
                ('role_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_role_view', to='auth.group')),
            ],
        ),
    ]
