# Generated by Django 6.0 on 2026-01-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rbac', '0006_devicegroupdjangoroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroupDjangoPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='django_permissions', to='rbac.devicegroup')),
                ('perm_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_perm_add', to='auth.permission')),
                ('perm_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_perm_change', to='auth.permission')),
                ('perm_delete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_perm_delete', to='auth.permission')),
                ('perm_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_perm_view', to='auth.permission')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceGroupDjangoRoles',
        ),
    ]
