# Generated by Django 6.0 on 2026-01-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this schedule was created'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='cron_expression',
            field=models.CharField(blank=True, help_text='For custom schedules: cron expression (minute hour day month day_of_week)', max_length=255),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='day_of_month',
            field=models.IntegerField(default=1, help_text='For monthly schedules: day of month (1-31)'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='day_of_week',
            field=models.CharField(default='0', help_text='For weekly schedules: 0=Sunday, 1=Monday, ..., 6=Saturday', max_length=7),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='description',
            field=models.TextField(blank=True, help_text='Explanation of when and why this schedule runs'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable this schedule'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='hour',
            field=models.IntegerField(default=0, help_text='Hour (0-23) when backup should execute'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='minute',
            field=models.IntegerField(default=0, help_text='Minute (0-59) when backup should execute'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='name',
            field=models.CharField(help_text='Display name for this schedule', max_length=128),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='schedule_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom_cron', 'Custom Cron')], default='daily', help_text='Type of recurrence pattern', max_length=20),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this schedule was last modified'),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='max_backups',
            field=models.IntegerField(blank=True, help_text='Keep only last N backups', null=True),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='max_days',
            field=models.IntegerField(blank=True, help_text='Delete backups older than N days', null=True),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='max_size_bytes',
            field=models.BigIntegerField(blank=True, help_text='Delete oldest backups when total size exceeds N bytes', null=True),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='name',
            field=models.CharField(help_text='Descriptive name for this retention policy', max_length=128),
        ),
    ]
