# Generated by Django 5.2.10 on 2026-01-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_backupschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupschedule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='Last time this schedule executed backups', null=True),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='next_run_at',
            field=models.DateTimeField(blank=True, help_text='Calculated next execution time (cached for frontend)', null=True),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
