# Generated by Django 6.0 on 2026-01-07 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text='Type of action (create, update, delete, etc.)', max_length=128),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when action occurred'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict, help_text='Additional context: changed fields, old/new values, etc.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='label_scope',
            field=models.JSONField(default=list, help_text='Labels of affected resource for access control filtering'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(help_text='Type of resource affected (Device, Backup, etc.)', max_length=128),
        ),
    ]
