# Generated by Django 6.0 on 2026-01-07 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardlayout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Layout creation timestamp'),
        ),
        migrations.AlterField(
            model_name='dashboardlayout',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default layout for all users'),
        ),
        migrations.AlterField(
            model_name='dashboardlayout',
            name='layout',
            field=models.JSONField(default=list, help_text='Dashboard widget configuration as JSON array'),
        ),
        migrations.AlterField(
            model_name='dashboardlayout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last modification timestamp'),
        ),
        migrations.AlterField(
            model_name='dashboardlayout',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User who customized this layout (null for default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of label purpose'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(help_text='Label name (Production, DMZ, etc.)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Profile creation timestamp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='dark', help_text='UI theme preference', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last modification timestamp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
