# Generated by Django 6.0 on 2026-01-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dashboardlayout_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
