# Generated by Django 6.0 on 2026-01-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_dashboard_layout_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bar_color', models.CharField(default='#1976D2', help_text='Hex color code for application title bar (e.g., #1976D2)', max_length=7)),
                ('dashboard_box_color', models.CharField(default='#424242', help_text='Hex color code for dashboard boxes (e.g., #424242)', max_length=7)),
                ('dashboard_nested_box_color', models.CharField(default='#2196F3', help_text='Hex color code for dashboard nested boxes (e.g., #2196F3)', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
