# Generated by Django 5.2.10 on 2026-01-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_themesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tick', models.DateTimeField(blank=True, help_text='Last time scheduler processed schedules', null=True)),
                ('is_running', models.BooleanField(default=False, help_text='Whether scheduler is currently running')),
                ('scheduler_pid', models.IntegerField(blank=True, help_text='Process ID of running scheduler', null=True)),
                ('last_restart_at', models.DateTimeField(blank=True, help_text='Last scheduler restart timestamp', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduler State',
                'verbose_name_plural': 'Scheduler State',
            },
        ),
        migrations.AlterField(
            model_name='dashboardlayout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dashboard_box_color',
            field=models.CharField(default='#1976D2', help_text='Hex color code for dashboard boxes (e.g., #1976D2)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
